version: "3.9"

services:
  collector:
    build: .
    command: python run.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  dashboard:
    build: .
    command: streamlit run src/dashboard/app.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    restart: unless-stopped
